CREATE TABLE IF NOT EXISTS shipments (
    id UUID PRIMARY KEY,
    origin VARCHAR(255) NOT NULL,
    destination VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    cost DECIMAL(12, 2) NOT NULL DEFAULT 0,
    revenue DECIMAL(12, 2) NOT NULL DEFAULT 0,
    weight DECIMAL(10, 2) NOT NULL DEFAULT 0,
    dimension_length DECIMAL(10, 2) NOT NULL DEFAULT 0,
    dimension_width DECIMAL(10, 2) NOT NULL DEFAULT 0,
    dimension_height DECIMAL(10, 2) NOT NULL DEFAULT 0,
    driver_name VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
