// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Shipment struct {
	ID              uuid.UUID
	Origin          string
	Destination     string
	Status          string
	Cost            pgtype.Numeric
	Revenue         pgtype.Numeric
	Weight          pgtype.Numeric
	DimensionLength pgtype.Numeric
	DimensionWidth  pgtype.Numeric
	DimensionHeight pgtype.Numeric
	DriverName      pgtype.Text
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}

type ShipmentEvent struct {
	ID          uuid.UUID
	ShipmentID  uuid.UUID
	Status      string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamp
}
