// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddShipmentEvent(ctx context.Context, arg AddShipmentEventParams) (ShipmentEvent, error)
	CreateShipment(ctx context.Context, arg CreateShipmentParams) (Shipment, error)
	GetShipmentByID(ctx context.Context, id uuid.UUID) (Shipment, error)
	GetShipmentEventHistory(ctx context.Context, shipmentID uuid.UUID) ([]ShipmentEvent, error)
}

var _ Querier = (*Queries)(nil)
