// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shipment_events.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addShipmentEvent = `-- name: AddShipmentEvent :one
INSERT INTO
    shipment_events (
        id,
        shipment_id,
        status,
        description
    )
VALUES ($1, $2, $3, $4) RETURNING id, shipment_id, status, description, created_at
`

type AddShipmentEventParams struct {
	ID          uuid.UUID
	ShipmentID  uuid.UUID
	Status      string
	Description *string
}

func (q *Queries) AddShipmentEvent(ctx context.Context, arg AddShipmentEventParams) (ShipmentEvent, error) {
	row := q.db.QueryRow(ctx, addShipmentEvent,
		arg.ID,
		arg.ShipmentID,
		arg.Status,
		arg.Description,
	)
	var i ShipmentEvent
	err := row.Scan(
		&i.ID,
		&i.ShipmentID,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getShipmentEventHistory = `-- name: GetShipmentEventHistory :many
SELECT id, shipment_id, status, description, created_at
FROM shipment_events
WHERE
    shipment_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetShipmentEventHistory(ctx context.Context, shipmentID uuid.UUID) ([]ShipmentEvent, error) {
	rows, err := q.db.Query(ctx, getShipmentEventHistory, shipmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShipmentEvent
	for rows.Next() {
		var i ShipmentEvent
		if err := rows.Scan(
			&i.ID,
			&i.ShipmentID,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
