// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shipment.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createShipment = `-- name: CreateShipment :one
INSERT INTO
    shipments (
        id,
        origin,
        destination,
        status,
        cost,
        revenue,
        weight,
        dimension_length,
        dimension_width,
        dimension_height,
        driver_name
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11
    ) RETURNING id, origin, destination, status, cost, revenue, weight, dimension_length, dimension_width, dimension_height, driver_name, created_at, updated_at
`

type CreateShipmentParams struct {
	ID              uuid.UUID
	Origin          string
	Destination     string
	Status          string
	Cost            pgtype.Numeric
	Revenue         pgtype.Numeric
	Weight          pgtype.Numeric
	DimensionLength pgtype.Numeric
	DimensionWidth  pgtype.Numeric
	DimensionHeight pgtype.Numeric
	DriverName      pgtype.Text
}

func (q *Queries) CreateShipment(ctx context.Context, arg CreateShipmentParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, createShipment,
		arg.ID,
		arg.Origin,
		arg.Destination,
		arg.Status,
		arg.Cost,
		arg.Revenue,
		arg.Weight,
		arg.DimensionLength,
		arg.DimensionWidth,
		arg.DimensionHeight,
		arg.DriverName,
	)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.Origin,
		&i.Destination,
		&i.Status,
		&i.Cost,
		&i.Revenue,
		&i.Weight,
		&i.DimensionLength,
		&i.DimensionWidth,
		&i.DimensionHeight,
		&i.DriverName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShipmentByID = `-- name: GetShipmentByID :one
SELECT id, origin, destination, status, cost, revenue, weight, dimension_length, dimension_width, dimension_height, driver_name, created_at, updated_at FROM shipments WHERE id = $1
`

func (q *Queries) GetShipmentByID(ctx context.Context, id uuid.UUID) (Shipment, error) {
	row := q.db.QueryRow(ctx, getShipmentByID, id)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.Origin,
		&i.Destination,
		&i.Status,
		&i.Cost,
		&i.Revenue,
		&i.Weight,
		&i.DimensionLength,
		&i.DimensionWidth,
		&i.DimensionHeight,
		&i.DriverName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
